### ISSUE TITLE
Inducción Matemática

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-isaias-paola-ariadna-arisbeth#1]
[induccion_matematica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-isaias-paola-ariadna-arisbeth/files/13223354/induccion_matematica.pdf)

**Comment by bibiana-m** [comment]
Portadas: 25%
Procedimientos: 25%
Figuras e ilustraciones: 22%
Resultado y conclusiones: 25%

Calificación: 97% / 10 * 20 = 19.4

Comentario: buen trabajo. favor de poner mas ilustraciones

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
