### ISSUE TITLE
MAPAS DE KARNAUGHT

### ISSUE THREAD

**Issue by 23620030** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-isaias-paola-ariadna-arisbeth#2]
[MAPAS DE KARNOT 1docx.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-isaias-paola-ariadna-arisbeth/files/13621312/MAPAS.DE.KARNOT.1docx.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
